import * as Tabs from "@radix-ui/react-tabs";
import { useFetcher } from "@remix-run/react";
import {
  useAnchorWallet,
  useConnection,
  useWallet,
} from "@solana/wallet-adapter-react";
import { LAMPORTS_PER_SOL } from "@solana/web3.js";
import { ChangeEvent, useEffect, useState } from "react";

import SceneWithModel from "~/components/3d/SceneWithModel";
import {
  Button,
  Field,
  Input,
  Meta,
  Notice,
  Page,
  PageHeader,
  Status,
  Textarea,
} from "~/components/ui";
import { NftMetadata } from "~/types/nft";
import { useSolanaNetwork } from "~/lib/network";

import { loadBlobFromLocalStorage } from "../utils/saveBlob";

interface ActionData {
  imageUrl?: string;
}

export default function GenerateAvatar() {
  const [prompt, setPrompt] = useState("");
  const [previewUrl, setPreviewUrl] = useState("");
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [uploadedPreviewUrl, setUploadedPreviewUrl] = useState("");
  const [nftName, setNftName] = useState("");
  const [nftSymbol, setNftSymbol] = useState("");
  const [nftDescription, setNftDescription] = useState("");
  const [nftMaxSupply, setNftMaxSupply] = useState("");
  const [nftMintFee, setNftMintFee] = useState("");
  const [minting, setMinting] = useState(false);
  const [tabValue, setTabValue] = useState<"upload" | "generate">("upload");
  const [notice, setNotice] = useState<
    { tone: "success" | "error"; text: string; href?: string } | null
  >(null);

  const { publicKey } = useWallet();
  const anchorWallet = useAnchorWallet();
  const { connection } = useConnection();
  const { buildExplorerTxUrl, clusterLabel } = useSolanaNetwork();
  const fetcher = useFetcher<ActionData>();

  useEffect(() => {
    if (previewUrl) {
      setTabValue("generate");
    }
  }, [previewUrl]);

  useEffect(() => {
    if (fetcher.data?.imageUrl) {
      setPreviewUrl(fetcher.data.imageUrl);
    }
  }, [fetcher.data]);

  const hasPreview = Boolean(previewUrl || uploadedPreviewUrl);

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) {
      return;
    }

    setUploadedFile(file);
    setUploadedPreviewUrl(URL.createObjectURL(file));
    setPreviewUrl("");
  };

  async function uploadFile(file: File): Promise<string> {
    const formData = new FormData();
    formData.append("file", file);

    const res = await fetch("/api/upload-metadata", {
      method: "POST",
      body: formData,
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`File upload failed: ${text}`);
    }

    const { files } = await res.json();
    return files[0].uri;
  }

  const handleDeploy = async () => {
    if (!publicKey || !anchorWallet) return;

    setNotice(null);
    setMinting(true);

    try {
      const blobPreview = loadBlobFromLocalStorage();
      if (!blobPreview) {
        throw new Error("No preview image found in localStorage.");
      }

      const filePreview = new File([blobPreview], "preview.png", {
        type: blobPreview.type,
      });
      const previewIpfsLink = await uploadFile(filePreview);
      const previewIpfsUri = previewIpfsLink;

      let modelIpfsUri = "";
      if (uploadedFile) {
        const modelIpfsLink = await uploadFile(uploadedFile);
        modelIpfsUri = modelIpfsLink;
        console.log("Uploaded model URI:", modelIpfsUri);
      }

      const metadata: NftMetadata = {
        name: nftName || `3D Avatar ${Date.now()}`,
        symbol: nftSymbol || "AVA3D",
        description:
          nftDescription || "A unique 3D avatar NFT generated by Ekza Space",
        image: previewIpfsUri,
        animation_url: modelIpfsUri,
        attributes: [],
        properties: {
          files: [
            { uri: previewIpfsUri, type: "image/png" },
            { uri: modelIpfsUri, type: "model/gltf-binary" },
          ],
          category: "vrmodel",
          creators: [{ address: publicKey.toBase58(), share: 100 }],
        },
      };

      const uploadRes = await fetch("/api/upload-metadata", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(metadata),
      });

      if (!uploadRes.ok) {
        const errorText = await uploadRes.text();
        throw new Error(`Metadata upload failed: ${errorText}`);
      }

      const uploadJson = await uploadRes.json();
      const metadataUri = uploadJson.ipfsHash;
      console.log("Metadata uploaded: ", uploadJson);

      try {
        const [anchor, { default: minterClient }] = await Promise.all([
          import("@coral-xyz/anchor"),
          import("avatars-sdk/minter"),
        ]);
        const provider = new anchor.AnchorProvider(
          connection,
          anchorWallet as any,
          anchor.AnchorProvider.defaultOptions()
        );
        const program = new anchor.Program(
          minterClient.idlJson as any,
          provider
        );
        // @ts-ignore
        const minter = minterClient.create(provider, program);

        const maxSupplyBn = new anchor.BN(nftMaxSupply || "1", 10);
        const mintFeeLamports = new anchor.BN(
          Math.round(parseFloat(nftMintFee || "0") * LAMPORTS_PER_SOL)
        );

        const { avatarDataPda, signature: initSig } =
          await minter.initializeAvatar({
            ipfsHash: metadataUri,
            maxSupply: maxSupplyBn,
            mintingFeePerMint: mintFeeLamports,
          });

        setNotice({
          tone: "success",
          text: `Collection deployed. Avatar PDA ${avatarDataPda.toBase58()}`,
          href: buildExplorerTxUrl(initSig),
        });
      } catch (sdkErr: any) {
        setNotice({
          tone: "error",
          text: `Deploy failed: ${sdkErr.message}`,
        });
        console.error("SDK mint failed:", sdkErr);
        setMinting(false);
        return;
      }
    } catch (err: any) {
      console.error("Client: Error in handleDeploy:", err);
      setNotice({
        tone: "error",
        text: `Deploy failed before signing: ${err.message}`,
      });
    } finally {
      setMinting(false);
    }
  };

  const previewNode = uploadedFile?.name.match(/\.(glb|vrm)$/i) ? (
    <div className="h-[440px] border border-[rgb(var(--line))] bg-[rgb(var(--surface-2))]">
      <SceneWithModel
        file={URL.createObjectURL(uploadedFile)}
        screenshot={true}
      />
    </div>
  ) : hasPreview ? (
    <div className="flex h-[440px] items-center justify-center border border-[rgb(var(--line))] bg-[rgb(var(--surface-2))] p-4">
      <img
        src={previewUrl || uploadedPreviewUrl}
        alt="Avatar preview"
        className="max-h-full w-auto object-contain"
      />
    </div>
  ) : (
    <div className="flex h-[440px] flex-col items-center justify-center gap-3 border border-dashed border-[rgba(var(--line-strong),0.28)] p-6 text-center">
      <span className="ui-label">Nothing to show yet</span>
      <p className="ui-copy-sm max-w-xs">
        Pick a .glb or .vrm file in step 01. The preview image sent to IPFS is
        captured from this scene.
      </p>
    </div>
  );

  return (
    <Page>
      <PageHeader
        eyebrow="Deploy"
        title={
          <>
            Publish a 3D
            <br />
            avatar collection.
          </>
        }
        lede="Upload a model, describe it, set supply and price. The metadata goes to IPFS and the collection is initialized on-chain."
        meta={
          <>
            <Meta label="Network" value={clusterLabel} />
            <Meta label="Fee unit" value="SOL" />
            <Status tone={publicKey ? "ok" : "error"}>
              {publicKey ? "Wallet connected" : "Wallet required"}
            </Status>
          </>
        }
      />

      {notice ? (
        <Notice tone={notice.tone} className="mt-8">
          <div className="space-y-2">
            <p className="break-all">{notice.text}</p>
            {notice.href ? (
              <a
                href={notice.href}
                target="_blank"
                rel="noopener noreferrer"
                className="ui-link inline-block text-sm"
              >
                Open in Solana Explorer ↗
              </a>
            ) : null}
          </div>
        </Notice>
      ) : null}

      <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(0,460px)]">
        <div className="lg:sticky lg:top-24 lg:self-start">
          <div className="mb-3 flex items-end justify-between border-b border-[rgb(var(--line))] pb-3">
            <h2 className="ui-h3">Preview</h2>
            <span className="ui-label">
              {hasPreview ? "Ready" : "Waiting for a model"}
            </span>
          </div>
          {previewNode}
        </div>

        <div className="space-y-8">
          <section>
            <StepHeading step="01" title="Model" />
            <Tabs.Root
              value={tabValue}
              onValueChange={(value) => {
                setTabValue(value as "upload" | "generate");
                setPreviewUrl("");
                setUploadedPreviewUrl("");
              }}
              className="space-y-5"
            >
              <Tabs.List className="flex gap-6 border-b border-[rgb(var(--line))]">
                <Tabs.Trigger value="upload" className="ui-navlink" >
                  Upload a file
                </Tabs.Trigger>
                <Tabs.Trigger value="generate" className="ui-navlink">
                  Generate (soon)
                </Tabs.Trigger>
              </Tabs.List>

              <Tabs.Content value="upload" className="space-y-4">
                <Field
                  label="3D asset"
                  hint="Accepted formats: .glb and .vrm."
                >
                  <Input
                    type="file"
                    accept=".vrm,.glb,model/gltf-binary"
                    onChange={handleFileChange}
                    className="cursor-pointer py-2.5"
                  />
                </Field>
                <p className="ui-copy-sm">
                  Nothing to test with?{" "}
                  <a
                    href="https://drive.google.com/drive/folders/11oQ8pwVMV9inSVV9cGceI8xTusDxhPC3?usp=drive_link"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="ui-link"
                  >
                    Download sample models
                  </a>
                  .
                </p>
              </Tabs.Content>

              <Tabs.Content value="generate" className="space-y-4">
                <fetcher.Form method="post" className="space-y-4">
                  <Field
                    label="Prompt"
                    hint="Model generation is not wired up yet — the field is here to shape the flow."
                  >
                    <Textarea
                      name="prompt"
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      placeholder="Describe the avatar you want..."
                      rows={4}
                      disabled
                    />
                  </Field>
                  <Button variant="secondary" disabled className="w-full">
                    Generate preview · coming soon
                  </Button>
                </fetcher.Form>
              </Tabs.Content>
            </Tabs.Root>
          </section>

          <section>
            <StepHeading step="02" title="Collection details" />
            <MetadataFields
              nftName={nftName}
              setNftName={setNftName}
              nftSymbol={nftSymbol}
              setNftSymbol={setNftSymbol}
              nftDescription={nftDescription}
              setNftDescription={setNftDescription}
              nftMaxSupply={nftMaxSupply}
              setNftMaxSupply={setNftMaxSupply}
              nftMintFee={nftMintFee}
              setNftMintFee={setNftMintFee}
            />
          </section>

          <section>
            <StepHeading step="03" title="Deploy" />
            <Button
              onClick={handleDeploy}
              disabled={minting || !hasPreview || !publicKey}
              className="w-full"
            >
              {minting ? "Deploying…" : "Deploy collection"}
            </Button>
            {!publicKey ? (
              <p className="mt-3 text-sm font-medium text-[rgb(var(--danger))]">
                Connect a wallet to deploy.
              </p>
            ) : !hasPreview ? (
              <p className="ui-copy-sm mt-3">
                Upload a model first — the preview image is captured from the 3D
                scene and pinned together with the metadata.
              </p>
            ) : null}
          </section>
        </div>
      </div>
    </Page>
  );
}

function StepHeading({ step, title }: { step: string; title: string }) {
  return (
    <div className="mb-4 flex items-baseline gap-3 border-b border-[rgb(var(--line))] pb-3">
      <span className="bg-[rgb(var(--accent))] px-1.5 py-0.5 font-mono text-[10px] font-bold tabular-nums tracking-[0.12em] text-[rgb(var(--accent-ink))]">
        {step}
      </span>
      <h2 className="ui-h3">{title}</h2>
    </div>
  );
}

function MetadataFields(props: {
  nftName: string;
  setNftName: (value: string) => void;
  nftSymbol: string;
  setNftSymbol: (value: string) => void;
  nftDescription: string;
  setNftDescription: (value: string) => void;
  nftMaxSupply: string;
  setNftMaxSupply: (value: string) => void;
  nftMintFee: string;
  setNftMintFee: (value: string) => void;
}) {
  const {
    nftName,
    setNftName,
    nftSymbol,
    setNftSymbol,
    nftDescription,
    setNftDescription,
    nftMaxSupply,
    setNftMaxSupply,
    nftMintFee,
    setNftMintFee,
  } = props;

  const infinite = nftMaxSupply === "18446744073709551615";

  return (
    <div className="grid gap-5">
      <Field label="Name" hint="Up to 32 bytes — shown on the market card.">
        <Input
          type="text"
          placeholder="Neon Runners"
          value={nftName}
          onChange={(e) => setNftName(e.target.value)}
        />
      </Field>
      <Field label="Symbol" optional hint="Short ticker, up to 10 bytes.">
        <Input
          type="text"
          placeholder="AVA3D"
          value={nftSymbol}
          onChange={(e) => setNftSymbol(e.target.value)}
        />
      </Field>
      <Field label="Description" optional>
        <Textarea
          placeholder="What is this collection about?"
          rows={3}
          value={nftDescription}
          onChange={(e) => setNftDescription(e.target.value)}
        />
      </Field>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field
          label="Max supply"
          hint="How many copies can ever be minted."
        >
          <Input
            type="text"
            inputMode="numeric"
            placeholder="64"
            value={infinite ? "∞" : nftMaxSupply}
            onChange={(e) => setNftMaxSupply(e.target.value)}
            disabled={infinite}
          />
        </Field>
        <Field label="Mint fee" hint="In SOL, per mint. 0 makes it free.">
          <Input
            type="number"
            min="0"
            step="0.001"
            placeholder="0.001"
            value={nftMintFee}
            onChange={(e) => setNftMintFee(e.target.value)}
          />
        </Field>
      </div>

      <label className="flex cursor-pointer items-center gap-3 border border-[rgb(var(--line))] px-4 py-3">
        <input
          type="checkbox"
          className="h-4 w-4 accent-[rgb(var(--accent-line))]"
          checked={infinite}
          onChange={(e) =>
            setNftMaxSupply(e.target.checked ? "18446744073709551615" : "")
          }
        />
        <span className="text-sm text-[rgb(var(--text-strong))]">
          Unlimited supply
        </span>
      </label>
    </div>
  );
}
