import * as Tabs from "@radix-ui/react-tabs";
import { useFetcher } from "@remix-run/react";
import { useAnchorWallet, useConnection, useWallet } from "@solana/wallet-adapter-react";
import { LAMPORTS_PER_SOL } from "@solana/web3.js";
import { ChangeEvent, useEffect, useState } from "react";

import SceneWithModel from "~/components/3d/SceneWithModel";
import { Badge, Button, Field, Input, PageSection, Panel, StatCard, Textarea } from "~/components/ui";
import { NftMetadata } from "~/types/nft";

import { loadBlobFromLocalStorage } from "../utils/saveBlob";

interface ActionData {
  imageUrl?: string;
}

export default function GenerateAvatar() {
  const [prompt, setPrompt] = useState("");
  const [previewUrl, setPreviewUrl] = useState("");
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [uploadedPreviewUrl, setUploadedPreviewUrl] = useState("");
  const [nftName, setNftName] = useState("");
  const [nftSymbol, setNftSymbol] = useState("");
  const [nftDescription, setNftDescription] = useState("");
  const [nftMaxSupply, setNftMaxSupply] = useState("");
  const [nftMintFee, setNftMintFee] = useState("");
  const [minting, setMinting] = useState(false);
  const [tabValue, setTabValue] = useState<"upload" | "generate">("upload");

  const { publicKey } = useWallet();
  const anchorWallet = useAnchorWallet();
  const { connection } = useConnection();
  const fetcher = useFetcher<ActionData>();

  useEffect(() => {
    if (previewUrl) {
      setTabValue("generate");
    }
  }, [previewUrl]);

  useEffect(() => {
    if (fetcher.data?.imageUrl) {
      setPreviewUrl(fetcher.data.imageUrl);
    }
  }, [fetcher.data]);

  const hasPreview = Boolean(previewUrl || uploadedPreviewUrl);

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) {
      return;
    }

    setUploadedFile(file);
    setUploadedPreviewUrl(URL.createObjectURL(file));
    setPreviewUrl("");
  };

  async function uploadFile(file: File): Promise<string> {
    const formData = new FormData();
    formData.append("file", file);

    const res = await fetch("/api/upload-metadata", {
      method: "POST",
      body: formData,
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`File upload failed: ${text}`);
    }

    const { files } = await res.json();
    return files[0].uri;
  }

  const handleDeploy = async () => {
    if (!publicKey || !anchorWallet) return;

    setMinting(true);

    try {
      const blobPreview = loadBlobFromLocalStorage();
      if (!blobPreview) {
        throw new Error("No preview image found in localStorage.");
      }

      const filePreview = new File([blobPreview], "preview.png", {
        type: blobPreview.type,
      });
      const previewIpfsLink = await uploadFile(filePreview);
      const previewIpfsUri = previewIpfsLink.substring(
        previewIpfsLink.lastIndexOf("/") + 1
      );

      let modelIpfsUri = "";
      if (uploadedFile) {
        const modelIpfsLink = await uploadFile(uploadedFile);
        modelIpfsUri = modelIpfsLink.substring(modelIpfsLink.lastIndexOf("/") + 1);
        console.log("Uploaded model hash:", modelIpfsUri);
      }

      const metadata: NftMetadata = {
        name: nftName || `3D Avatar ${Date.now()}`,
        symbol: nftSymbol || "AVA3D",
        description:
          nftDescription || "A unique 3D avatar NFT generated by Ekza Space",
        image: previewIpfsUri,
        animation_url: modelIpfsUri,
        attributes: [],
        properties: {
          files: [
            { uri: previewIpfsUri, type: "image/png" },
            { uri: modelIpfsUri, type: "model/gltf-binary" },
          ],
          category: "vrmodel",
          creators: [{ address: publicKey.toBase58(), share: 100 }],
        },
      };

      const uploadRes = await fetch("/api/upload-metadata", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(metadata),
      });

      if (!uploadRes.ok) {
        const errorText = await uploadRes.text();
        throw new Error(`Metadata upload failed: ${errorText}`);
      }

      const uploadJson = await uploadRes.json();
      const metadataUri = uploadJson.ipfsHash;
      console.log("Metadata uploaded: ", uploadJson);

      try {
        const [anchor, { default: minterClient }] = await Promise.all([
          import("@coral-xyz/anchor"),
          import("avatars-sdk/minter"),
        ]);
        const provider = new anchor.AnchorProvider(
          connection,
          anchorWallet as any,
          anchor.AnchorProvider.defaultOptions()
        );
        const program = new anchor.Program(minterClient.idlJson as any, provider);
        // @ts-ignore
        const minter = minterClient.create(provider, program);

        const maxSupplyBn = new anchor.BN(nftMaxSupply || "0", 10);
        const mintFeeLamports = new anchor.BN(
          Math.round(parseFloat(nftMintFee || "0") * LAMPORTS_PER_SOL)
        );

        const { avatarDataPda, signature: initSig } =
          await minter.initializeAvatar({
            ipfsHash: metadataUri,
            maxSupply: maxSupplyBn,
            mintingFeePerMint: mintFeeLamports,
          });

        alert(
          `✅ Avatar collection initialised!\n\nAvatar PDA:\n${avatarDataPda.toBase58()}\n\nTransaction:\nhttps://explorer.solana.com/tx/${initSig}?cluster=devnet`
        );
      } catch (sdkErr: any) {
        alert("Mint failed via SDK: " + sdkErr.message);
        console.error("SDK mint failed:", sdkErr);
        setMinting(false);
        return;
      }
    } catch (err: any) {
      console.error("Client: Error in handleDeploy:", err);
      alert("Mint failed (client-side exception): " + err.message);
    } finally {
      setMinting(false);
    }
  };

  const previewNode = uploadedFile?.name.match(/\.(glb|vrm)$/i) ? (
    <div className="h-[420px] overflow-hidden rounded-[24px] border border-[rgba(var(--line),0.6)]">
      <SceneWithModel file={URL.createObjectURL(uploadedFile)} screenshot={true} />
    </div>
  ) : hasPreview ? (
    <div className="overflow-hidden rounded-[24px] border border-[rgba(var(--line),0.6)] bg-[rgba(var(--surface-2),0.76)] p-4">
      <img
        src={previewUrl || uploadedPreviewUrl}
        alt="Avatar preview"
        className="mx-auto aspect-square h-auto max-h-[380px] w-full max-w-md rounded-[20px] object-contain"
      />
    </div>
  ) : (
    <div className="flex min-h-[320px] items-center justify-center rounded-[24px] border border-dashed border-[rgba(var(--line-strong),0.36)] bg-[rgba(var(--surface),0.58)]">
      <div className="space-y-3 text-center">
        <div className="ui-badge">Preview</div>
        <p className="ui-copy max-w-sm">
          Upload a `.glb` or `.vrm` avatar model to generate a preview-ready
          collection draft.
        </p>
      </div>
    </div>
  );

  return (
    <PageSection
      eyebrow="Collection Deployer"
      title="Publish a 3D avatar collection"
      description="Upload a model, shape the NFT metadata, and initialize a minter on devnet. The creation pipeline is intact, but the workspace is now much easier to navigate."
      actions={
        <>
          <Badge>{publicKey ? "Wallet ready" : "Wallet required"}</Badge>
          <Badge tone={hasPreview ? "success" : "default"}>
            {hasPreview ? "Preview ready" : "Awaiting asset"}
          </Badge>
        </>
      }
    >
      <div className="mb-6 grid gap-5 lg:grid-cols-3">
        <StatCard
          label="Mint flow"
          value="Browser SDK"
          hint="Metadata uploads and on-chain initialization still happen client-side."
        />
        <StatCard
          label="Preview"
          value={hasPreview ? "Prepared" : "Empty"}
          hint="Screenshots are still captured from the 3D scene."
        />
        <StatCard
          label="Fee unit"
          value="SOL"
          hint="Mint fee is converted to lamports before initializeAvatar."
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <Panel className="space-y-5">
          <div className="space-y-2">
            <div className="ui-label">Asset preview</div>
            <h2 className="font-display text-2xl font-semibold tracking-tight text-[rgb(var(--text-strong))]">
              Live deployment workspace
            </h2>
          </div>
          {previewNode}
        </Panel>

        <Panel className="space-y-5">
          <Tabs.Root
            value={tabValue}
            onValueChange={(value) => {
              setTabValue(value as "upload" | "generate");
              setPreviewUrl("");
              setUploadedPreviewUrl("");
            }}
            className="space-y-5"
          >
            <Tabs.List className="grid grid-cols-2 gap-3">
              <Tabs.Trigger
                value="upload"
                className="rounded-2xl border border-[rgba(var(--line),0.52)] px-4 py-3 text-sm font-medium text-[rgb(var(--text))] transition data-[state=active]:border-[rgba(var(--line-strong),0.58)] data-[state=active]:bg-[rgba(var(--accent),0.1)] data-[state=active]:text-[rgb(var(--text-strong))]"
              >
                Upload model
              </Tabs.Trigger>
              <Tabs.Trigger
                value="generate"
                className="rounded-2xl border border-[rgba(var(--line),0.52)] px-4 py-3 text-sm font-medium text-[rgb(var(--text))] transition data-[state=active]:border-[rgba(var(--line-strong),0.58)] data-[state=active]:bg-[rgba(var(--accent),0.1)] data-[state=active]:text-[rgb(var(--text-strong))]"
              >
                Generate idea
              </Tabs.Trigger>
            </Tabs.List>

            <Tabs.Content value="upload" className="space-y-5">
              <Field label="3D asset" hint="Supported formats: `.vrm`, `.glb`.">
                <Input
                  type="file"
                  accept=".vrm,.glb,model/gltf-binary"
                  onChange={handleFileChange}
                  className="cursor-pointer p-4"
                />
              </Field>
              <p className="ui-copy text-sm">
                Need something to test with?{" "}
                <a
                  href="https://drive.google.com/drive/folders/11oQ8pwVMV9inSVV9cGceI8xTusDxhPC3?usp=drive_link"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[rgb(var(--accent))]"
                >
                  Download sample models
                </a>
                .
              </p>
              <MetadataFields
                nftName={nftName}
                setNftName={setNftName}
                nftSymbol={nftSymbol}
                setNftSymbol={setNftSymbol}
                nftDescription={nftDescription}
                setNftDescription={setNftDescription}
                nftMaxSupply={nftMaxSupply}
                setNftMaxSupply={setNftMaxSupply}
                nftMintFee={nftMintFee}
                setNftMintFee={setNftMintFee}
              />
            </Tabs.Content>

            <Tabs.Content value="generate" className="space-y-5">
              <fetcher.Form method="post" className="space-y-4">
                <Field
                  label="Prompt"
                  hint="Generator UI stays present, but the actual generation endpoint is still unfinished."
                >
                  <Textarea
                    name="prompt"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="Describe the avatar you want..."
                    rows={4}
                  />
                </Field>
                <Button
                  onClick={() => alert("Sorry, this feature still in progress.")}
                  type="button"
                  variant="secondary"
                  className="w-full"
                >
                  Generate preview
                </Button>
                {!publicKey ? (
                  <p className="text-sm font-medium text-[rgb(var(--danger))]">
                    Connect your wallet to use generation and deployment actions.
                  </p>
                ) : null}
              </fetcher.Form>

              <MetadataFields
                nftName={nftName}
                setNftName={setNftName}
                nftSymbol={nftSymbol}
                setNftSymbol={setNftSymbol}
                nftDescription={nftDescription}
                setNftDescription={setNftDescription}
                nftMaxSupply={nftMaxSupply}
                setNftMaxSupply={setNftMaxSupply}
                nftMintFee={nftMintFee}
                setNftMintFee={setNftMintFee}
              />
            </Tabs.Content>
          </Tabs.Root>

          {hasPreview && publicKey ? (
            <Button onClick={handleDeploy} disabled={minting} className="w-full">
              {minting ? "Deploying collection..." : "Deploy collection"}
            </Button>
          ) : null}
        </Panel>
      </div>
    </PageSection>
  );
}

function MetadataFields(props: {
  nftName: string;
  setNftName: (value: string) => void;
  nftSymbol: string;
  setNftSymbol: (value: string) => void;
  nftDescription: string;
  setNftDescription: (value: string) => void;
  nftMaxSupply: string;
  setNftMaxSupply: (value: string) => void;
  nftMintFee: string;
  setNftMintFee: (value: string) => void;
}) {
  const {
    nftName,
    setNftName,
    nftSymbol,
    setNftSymbol,
    nftDescription,
    setNftDescription,
    nftMaxSupply,
    setNftMaxSupply,
    nftMintFee,
    setNftMintFee,
  } = props;

  const infinite = nftMaxSupply === "18446744073709551615";

  return (
    <div className="grid gap-4">
      <Field label="NFT Name">
        <Input
          type="text"
          placeholder="Avatar collection name"
          value={nftName}
          onChange={(e) => setNftName(e.target.value)}
        />
      </Field>
      <Field label="Symbol" hint="Optional short ticker shown inside metadata.">
        <Input
          type="text"
          placeholder="AVA3D"
          value={nftSymbol}
          onChange={(e) => setNftSymbol(e.target.value)}
        />
      </Field>
      <Field label="Description">
        <Textarea
          placeholder="Describe the collection"
          rows={3}
          value={nftDescription}
          onChange={(e) => setNftDescription(e.target.value)}
        />
      </Field>
      <div className="grid gap-4 md:grid-cols-[1fr_auto]">
        <Field label="Max Supply">
          <Input
            type="text"
            placeholder="64"
            value={infinite ? "∞" : nftMaxSupply}
            onChange={(e) => setNftMaxSupply(e.target.value)}
            disabled={infinite}
          />
        </Field>
        <label className="ui-panel-muted flex items-center gap-3 px-4 py-3">
          <input
            type="checkbox"
            className="h-4 w-4"
            checked={infinite}
            onChange={(e) =>
              setNftMaxSupply(e.target.checked ? "18446744073709551615" : "")
            }
          />
          <span className="ui-copy whitespace-nowrap text-sm">Infinity</span>
        </label>
      </div>
      <Field label="Mint Fee (SOL)">
        <Input
          type="number"
          placeholder="0.001"
          value={nftMintFee}
          onChange={(e) => setNftMintFee(e.target.value)}
        />
      </Field>
    </div>
  );
}